version: '3'

services:
  neo4j:
    image: neo4j:latest
    network_mode: "bridge"
    ports:
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    volumes:
      - ./plugins:/plugins
      - ./data:/data
      - ./import:/import
  web:
    image: tomcat:latest
    # Environment variables do not appear to be getting loaded the first time Tomcat starts!
    restart: on-failure
    ports:
      - "8081:8080"
    volumes:
      #- ./out/artifacts/CovidWar:/usr/local/tomcat/webapps
      #- ./out/artifacts/Covid:/usr/local/tomcat/webapps
      - ./target/test-classes:/usr/local/tomcat/webapps
    links:
      - neo4j


